title: Swapnil Kumar
subtitle: "Product Manager & Engineer"
name: "Swapnil Kumar"
description: "PM & Engineering projects across AWS, Inshorts, Interview Kickstart, Dunzo, and Flipkart"
url: "https://swa311096.github.io"
baseurl: "/work-portfolio"

remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "air"

# Site Author
author:
  name: "Swapnil Kumar"
  bio: "Product Manager • USC Marshall MBA • IIT Kharagpur"
  location: "Los Angeles, CA"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/swapnil-kumar1/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/swa311096"

# Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/swapnil-kumar1/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/swa311096"

# Reading Files
include:
  - _pages

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true
